import { cn } from '@/shared/lib/utils'
import type { Metadata } from 'next'

import { Inter } from 'next/font/google'
import { Providers } from './_providers'

import Header from '@/shared/ui/header'
import './globals.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Авторизация',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={cn(inter.className, 'flex items-center justify-center')}>
				<Providers>
					<Header />
					{children}
				</Providers>
			</body>
		</html>
	)
}
